add 125-zeze1004
all1m-algorithm-study/LeetCode-Solutions pull request #47
Opened 2021-02-16 08:16 UTC by zeze1004

2021-02-17 06:00 UTC, powergee requested changes
PR 해주셔서 감사합니다~ 그런데 일부 파일에서 잘못된 부분이 있어 코멘트를 추가하였습니다. 수정해주시면 바로 반영하겠습니다!

2021-02-17 06:00 UTC, kim-jhyeon commented on solutions/125/125-zeze1004.md
> +소스코드 : [link](./125-zeze1004.py)
링크에서 가르키는 파일이 존재하지 않습니다. 윗 문단에서 설명하고 있는 풀이를 고려했을 때, `125-zeze1004(1).py`여야 할 것 같습니다!

2021-02-17 06:00 UTC, kim-jhyeon commented on solutions/125/125-zeze1004.md
> +소스코드 : [link](./125-zeze1004.py)
링크에서 가르키는 파일이 존재하지 않습니다. 윗 문단에서 설명하고 있는 풀이를 고려했을 때, `125-zeze1004(2).py`여야 할 것 같습니다!

2021-02-17 06:00 UTC, kim-jhyeon commented on solutions/344/344-zeze1004.md
> +시간복잡도 : O(1)
`reverse`의 시간복잡도는 `O(n)`이고, 다른 두가지 풀이에서도 Linear하게 문자열을 탐색하고 있으므로, 시간복잡도가 잘못된 것 같습니다! :cry: 

아래 문서에서 `reverse`의 시간복잡도를 참고하였습니다.

https://python-reference.readthedocs.io/en/latest/docs/list/reverse.html

2021-02-17 09:01 UTC, zeze1004 commented
헉 죄송합니다ㅠㅠ 수정하고 다시 pr 날리겠습니다!

2021-02-17 09:01 UTC, zeze1004 commented
앗 pr은 더 못 날리고 수정한 후 커밋만 새로 날리면 되나요?

2021-02-17 09:07 UTC, powergee commented
> 앗 pr은 더 못 날리고 수정한 후 커밋만 새로 날리면 되나요?

넵, 커밋만 하셔도 이 PR에 반영됩니다!

2021-02-21 14:26 UTC, powergee commented
@zeze1004 님, 오늘 LeetCode-Solutions 활동이 종료되고 최종 점수를 계산할 예정이라, 곧 PR을 머지해야 할 것 같습니다! 수정 커밋을 해주실 수 있으신가요?

(LeetCode-Solutions 활동은 오늘 11시 59분까지 진행되는 활동이지만, 실수에 대한 정정을 하는 커밋은 이후에도 인정할 예정이므로 꼭 오늘까지 수정해주시지는 않으셔도 됩니다!)

2021-02-23 12:01 UTC, zeze1004 commented
수정 후 커밋했습니다. 늦어서 죄송합니다!

2021-02-23 14:27 UTC, powergee commented
넵, 확인했습니다. 머지하겠습니다~

2021-02-23 14:27 UTC, merged